USE [master]
GO

/****** Object:  Database [db_dengue]    Script Date: 17/08/2024 14:17:09 ******/
CREATE DATABASE [db_dengue]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_dengue', FILENAME = N'C:\Users\kenzo\db_dengue.mdf' , SIZE = 5775360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_dengue_log', FILENAME = N'C:\Users\kenzo\db_dengue_log.ldf' , SIZE = 17637376KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_dengue].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_dengue] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_dengue] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_dengue] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_dengue] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_dengue] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_dengue] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_dengue] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_dengue] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_dengue] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_dengue] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_dengue] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_dengue] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_dengue] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_dengue] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_dengue] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_dengue] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_dengue] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_dengue] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_dengue] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_dengue] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_dengue] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_dengue] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_dengue] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_dengue] SET  MULTI_USER 
GO

ALTER DATABASE [db_dengue] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_dengue] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_dengue] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_dengue] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_dengue] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_dengue] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [db_dengue] SET QUERY_STORE = OFF
GO

ALTER DATABASE [db_dengue] SET  READ_WRITE 
GO


