WITH DELTAS AS (
    SELECT 
        A.NM_MUNICIPIO AS MUN_MUNICIPIO, 
        A.LATITUDE AS MUN_LATITUDE, 
        A.LONGITUDE AS MUN_LONGITUDE, 
        B.NM_MUNICIPIO AS INMET_MUNICIPIO, 
        B.LATITUDE AS INMET_LATITUDE, 
        B.LONGITUDE AS INMET_LONGITUDE,
        dbo.haversine(A.LATITUDE, A.LONGITUDE, B.LATITUDE, B.LONGITUDE) AS DISTANCIA
    FROM 
        db_dengue.Geral.MUNICIPIO A
    CROSS JOIN 
        db_dengue.INMET.Municipios B
    WHERE 
        A.UF = 35 -- Apenas SP
),
DISTANCIAS_MINIMAS AS (
    SELECT 
        MUN_MUNICIPIO,
        MIN(DISTANCIA) AS DISTANCIA_MIN
    FROM 
        DELTAS
    GROUP BY 
        MUN_MUNICIPIO
)
SELECT
    DELTAS.MUN_MUNICIPIO AS MUNICIPIO_DE, 
    DELTAS.INMET_MUNICIPIO AS MUNICIPIO_PARA,  
    DELTAS.DISTANCIA
FROM
    DELTAS
JOIN 
    DISTANCIAS_MINIMAS
ON 
    DELTAS.MUN_MUNICIPIO = DISTANCIAS_MINIMAS.MUN_MUNICIPIO
    AND DELTAS.DISTANCIA = DISTANCIAS_MINIMAS.DISTANCIA_MIN;
