TRUNCATE TABLE [db_dengue].[Dengue].[Dataset]

INSERT INTO [db_dengue].[Dengue].[Dataset] (
	SK_DENGUE,
	DT_REF,
	CD_MUNICIPIO,
	NM_MUNICIPIO,
	UF,
	ID_OCUPA_N,
	FEBRE,
	HOSPITALIZACAO,
	CLASSI_FIN,
	CRITERIO,
	DT_OBITO,
	DT_ALRM,
	DT_GRAV,	
	PRECIPITACAO_TOTAL_MENSAL,	
	TEMP_MEDIA_MENSAL,	
	TEMP_MAX_MENSAL,	
	TEMP_MIN_MENSAL,	
	VENTO_RAJADA_MAX_MENSAL,	
	VENTO_VLC_MEDIA_MENSAL
)

SELECT 
ROW_NUMBER() OVER(ORDER BY DT_REF, CD_MUNICIPIO ASC) SK_DENGUE,
DT_REF,
CD_MUNICIPIO,
NM_MUNICIPIO,
UF,
ID_OCUPA_N,
FEBRE,
HOSPITALIZ HOSPITALIZACAO,
CLASSI_FIN,
CRITERIO,
DT_OBITO,
DT_ALRM,
DT_GRAV,	
PRECIPITACAO_TOTAL_MENSAL,	
TEMP_MEDIA_MENSAL,	
TEMP_MAX_MENSAL,	
TEMP_MIN_MENSAL,	
VENTO_RAJADA_MAX_MENSAL,	
VENTO_VLC_MEDIA_MENSAL
FROM db_dengue.SINAN.DENGBR_TOTAL SINAN
INNER JOIN db_dengue.Geral.DeParaMunicipio DEPARA ON SINAN.CD_MUNICIPIO = LEFT(DEPARA.DE_CD_MUNICIPIO, 6)
INNER JOIN db_dengue.INMET.Dados_SP_Mensal INMET ON INMET.MUNICIPIO = DEPARA.PARA_NM_MUNICIPIO AND SINAN.DT_INVEST = INMET.DT_REF
ORDER BY DT_REF, CD_MUNICIPIO
