UPDATE db_dengue.INMET.Importacao_Dados_SP
SET HR_REF_UTC = SUBSTRING(HR_REF_UTC, 1, 2) + ':' + SUBSTRING(HR_REF_UTC, 3, 2)

UPDATE A 
SET PRECIPITACAO_TOTAL = '0' + PRECIPITACAO_TOTAL
FROM db_dengue.INMET.Importacao_Dados_SP A
WHERE PRECIPITACAO_TOTAL LIKE ',%'

UPDATE A 
SET VENTO_RAJADA_MAX = '0' + VENTO_RAJADA_MAX
FROM db_dengue.INMET.Importacao_Dados_SP A
WHERE VENTO_RAJADA_MAX LIKE ',%'

UPDATE A 
SET VENTO_VLC_HR = '0' + VENTO_VLC_HR
FROM db_dengue.INMET.Importacao_Dados_SP A
WHERE VENTO_VLC_HR LIKE ',%'

UPDATE A
SET PRECIPITACAO_TOTAL = REPLACE(PRECIPITACAO_TOTAL, ',', '.')
FROM db_dengue.INMET.Importacao_Dados_SP A
WHERE PRECIPITACAO_TOTAL LIKE '%,%'

UPDATE A
SET TEMPERATURA = REPLACE(TEMPERATURA, ',', '.')
FROM db_dengue.INMET.Importacao_Dados_SP A
WHERE TEMPERATURA LIKE '%,%'

UPDATE A
SET TEMP_MAX_HR_ANT = REPLACE(TEMP_MAX_HR_ANT, ',', '.')
FROM db_dengue.INMET.Importacao_Dados_SP A
WHERE TEMP_MAX_HR_ANT LIKE '%,%'

UPDATE A
SET TEMP_MIN_HR_ANT = REPLACE(TEMP_MIN_HR_ANT, ',', '.')
FROM db_dengue.INMET.Importacao_Dados_SP A
WHERE TEMP_MIN_HR_ANT LIKE '%,%'

UPDATE A
SET VENTO_RAJADA_MAX = REPLACE(VENTO_RAJADA_MAX, ',', '.')
FROM db_dengue.INMET.Importacao_Dados_SP A
WHERE VENTO_RAJADA_MAX LIKE '%,%'

UPDATE A
SET VENTO_VLC_HR = REPLACE(VENTO_VLC_HR, ',', '.')
FROM db_dengue.INMET.Importacao_Dados_SP A
WHERE VENTO_VLC_HR LIKE '%,%'
