CREATE VIEW [Dengue].[Analitica] AS

WITH CRITERIOS AS (
	SELECT
		[ID_CRITERIO], 
		[HOSPITALIZACAO], 
		[CLASSIFICADOR], 
		[CRITERIO], 
		[RESULTADO_SORO], 
		[RESULTADO_NS1], 
		[RESULTADO_PCR], 
		[AUTOCTONE], 
		[FEBRE], 
		[VOMITO], 
		[NAUSEA], 
		[SANGRAMENTO]
	FROM (
    SELECT 
        ID_CRITERIO, 
        NM_COLUNA, 
        NM_CRITERIO
    FROM [db_dengue].[Geral].[Criterio]
	) AS CRITERIO
	PIVOT 
	(
		MAX(NM_CRITERIO) 
		FOR NM_COLUNA IN ([HOSPITALIZACAO], [CLASSIFICADOR], [CRITERIO], [RESULTADO_SORO], [RESULTADO_NS1], [RESULTADO_PCR], [AUTOCTONE], [FEBRE], [VOMITO], [NAUSEA], [SANGRAMENTO])
	) AS X
)

SELECT 
	 DST.SK_DENGUE	
	,DST.DT_NOTIFICACAO	
	,DST.DT_INTERNACAO	
	,DST.DT_OBITO	
	,DST.DT_ALARME	
	,DST.DT_GRAVE	
	,DST.DT_SORO	
	,DST.DT_NS1	
	,DST.DT_PCR	
	,DST.DT_ENCERRAMENTO	
	,DST.CD_MUNICIPIO
	,MUN.NM_MUNICIPIO
	,DST.PROFISSAO	
	,HOSP.HOSPITALIZACAO	
	,CLS.CLASSIFICADOR	
	,CRI.CRITERIO	
	,RSS.RESULTADO_SORO	
	,NS1.RESULTADO_NS1	
	,PCR.RESULTADO_PCR	
	,ATC.AUTOCTONE	
	,FBR.FEBRE	
	,VMT.VOMITO	
	,NSA.NAUSEA	
	,SGM.SANGRAMENTO	
	,DST.PRECIPITACAO_TOTAL_MENSAL	
	,DST.TEMP_MEDIA_MENSAL	
	,DST.TEMP_MAX_MENSAL	
	,DST.TEMP_MIN_MENSAL	
	,DST.VENTO_RAJADA_MAX_MENSAL	
	,DST.VENTO_VLC_MEDIA_MENSAL
FROM 
	db_dengue.Dengue.Codificada DST
INNER JOIN 
	db_dengue.Geral.MUNICIPIO MUN ON
		DST.CD_MUNICIPIO = MUN.CD_MUNICIPIO
LEFT JOIN CRITERIOS HOSP ON DST.HOSPITALIZACAO = HOSP.ID_CRITERIO
LEFT JOIN CRITERIOS CLS ON DST.CLASSIFICADOR = CLS.ID_CRITERIO
LEFT JOIN CRITERIOS CRI ON DST.CRITERIO = CRI.ID_CRITERIO
LEFT JOIN CRITERIOS RSS ON DST.RESULTADO_SORO = RSS.ID_CRITERIO
LEFT JOIN CRITERIOS NS1 ON DST.RESULTADO_NS1 = NS1.ID_CRITERIO 
LEFT JOIN CRITERIOS PCR ON DST.RESULTADO_PCR = PCR.ID_CRITERIO
LEFT JOIN CRITERIOS ATC ON DST.AUTOCTONE = ATC.ID_CRITERIO 
LEFT JOIN CRITERIOS FBR ON DST.FEBRE = FBR.ID_CRITERIO 
LEFT JOIN CRITERIOS VMT ON DST.VOMITO = VMT.ID_CRITERIO 
LEFT JOIN CRITERIOS NSA ON DST.NAUSEA = NSA.ID_CRITERIO
LEFT JOIN CRITERIOS SGM ON DST.SANGRAMENTO = SGM.ID_CRITERIO
