CREATE VIEW [INMET].[Dados_SP_Diaria] AS


	SELECT 
			DT_REF,
			MUNICIPIO,
			ROUND(AVG(PRECIPITACAO_TOTAL), 2, 1) PRECIPITACAO_TOTAL_DIARIA,
			ROUND(AVG(TEMPERATURA), 2, 1) TEMP_MEDIA_DIARIA,
			ROUND(MAX(TEMP_MAX_HR_ANT), 2, 1) TEMP_MAX_DIARIA,
			ROUND(MIN(TEMP_MIN_HR_ANT), 2, 1) TEMP_MIN_DIARIA,
			ROUND(MAX(VENTO_RAJADA_MAX), 2, 1) VENTO_RAJADA_MAX_DIARIA,
			ROUND(AVG(VENTO_VLC_HR), 2, 1) VENTO_VLC_MEDIA_DIARIA
		FROM 
			[db_dengue].[INMET].[Dados_SP]
		WHERE
			MUNICIPIO != 'SAO PAULO - MIRANTE'
		GROUP BY
			DT_REF, 
			MUNICIPIO
