CREATE VIEW [INMET].[Dados_SP_Diaria] AS


	SELECT 
			DT_REF,
			MUNICIPIO,
			ROUND(AVG(IIF(PRECIPITACAO_TOTAL = -9999.00, NULL, PRECIPITACAO_TOTAL)), 2, 1) PRECIPITACAO_TOTAL_DIARIA,
			ROUND(AVG(IIF(TEMPERATURA = -9999.00, NULL, TEMPERATURA)), 2, 1) TEMP_MEDIA_DIARIA,
			ROUND(MAX(IIF(TEMP_MAX_HR_ANT = -9999.00, NULL, TEMP_MAX_HR_ANT)), 2, 1) TEMP_MAX_DIARIA,
			ROUND(MIN(IIF(TEMP_MIN_HR_ANT = -9999.00, NULL, TEMP_MIN_HR_ANT)), 2, 1) TEMP_MIN_DIARIA,
			ROUND(MAX(IIF(VENTO_RAJADA_MAX = -9999.00, NULL, VENTO_RAJADA_MAX)), 2, 1) VENTO_RAJADA_MAX_DIARIA,
			ROUND(AVG(IIF(VENTO_VLC_HR = -9999.00, NULL, VENTO_VLC_HR)), 2, 1) VENTO_VLC_MEDIA_DIARIA
		FROM 
			[db_dengue].[INMET].[Dados_SP]
		WHERE
			MUNICIPIO != 'SAO PAULO - MIRANTE'
		GROUP BY
			DT_REF, 
			MUNICIPIO
